apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: kafka
spec:
  hosts:
  - my-cluster-kafka-bootstrap.amq-streams.svc.cluster.local
  location: MESH_EXTERNAL
  ports:
    - name: tcp-clients
      number: 9092
      protocol: tcp
  resolution: NONE
